### ISSUE TITLE
Example EMR sensor DAG failing on KubernetesExecutor deployment

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#1058]
The failures logs are:
```
[2023-05-08, 03:55:16 UTC] {emr.py:502} INFO - Poking step s-2HIXLB08Q7ZCZ on cluster j-379IRTS1ZVJX2
[2023-05-08, 03:55:16 UTC] {emr.py:74} INFO - Job flow currently CANCELLED
[2023-05-08, 03:55:16 UTC] {manager.py:65} WARNING - Unable to find an extractor. task_type=EmrStepSensorAsync airflow_dag_id=example_emr_sensor task_id=watch_step airflow_run_id=manual__2023-05-08T03:45:20.091318+00:00 
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING - Exception in thread Thread-2 (on_failure):
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING - Traceback (most recent call last):
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     self.run()
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/threading.py", line 953, in run
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     self._target(*self._args, **self._kwargs)
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/site-packages/openlineage/airflow/listener.py", line 175, in on_failure
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     adapter.fail_task(
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/site-packages/openlineage/airflow/adapter.py", line 195, in fail_task
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     event = RunEvent(
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "<attrs generated init openlineage.client.run.RunEvent>", line 17, in __init__
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/site-packages/openlineage/client/run.py", line 83, in check
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     parser.isoparse(value)
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 37, in func
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     return f(self, str_in, *args, **kwargs)
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 134, in isoparse
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     components, pos = self._parse_isodate(dt_str)
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 208, in _parse_isodate
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     return self._parse_isodate_common(dt_str)
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 213, in _parse_isodate_common
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING -     len_str = len(dt_str)
[2023-05-08, 03:55:16 UTC] {logging_mixin.py:149} WARNING - TypeError: object of type 'NoneType' has no len()
[2023-05-08, 03:55:16 UTC] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/astronomer/providers/amazon/aws/sensors/emr.py", line 82, in execute
    if not self.poke(context):
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/amazon/aws/sensors/emr.py", line 80, in poke
    raise AirflowException(f"EMR job failed: {self.failure_message_from_response(response)}")
airflow.exceptions.AirflowException: EMR job failed: None
[2023-05-08, 03:55:16 UTC] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=example_emr_sensor, task_id=watch_step, execution_date=20230508T034520, start_date=20230508T035515, end_date=20230508T035516
[2023-05-08, 03:55:16 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 8099 for task watch_step (EMR job failed: None; 16)
[2023-05-08, 03:55:16 UTC] {local_task_job_runner.py:232} INFO - Task exited with return code 1
```

**Comment by Lee-W** [comment]
HI @pankajkoti , I'm afraid I'm unable to reproduce for now. Should we close it and reopen it if we encounter it again?
![圖片](https://github.com/astronomer/astronomer-providers/assets/5144808/236311d2-19ab-459d-b1d9-56686e05a397)

**Comment by pankajkoti** [comment]
yes, makes sense. Let's reopen later if we see this again. Thank you for testing this!
