### ISSUE TITLE
Bug : BigQueryGetDataOperator output is not getting casted to respective data types

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astronomer-providers#127]
The result of the BigQueryGetDataOperator is dict[str,str] where column types are int or date field in BigQuery. Need to change the output to cast to the big query column types.

**Comment by pankajastro** [comment]
Step to reproduce 
- Create bigquery table having a non-string column 

Query to insert data in bigquery table
```
INSERT `gcp-project.gcp_example_dataset.dummy_table` (name_str, value_int, value_float, value_numeric, value_boolean, value_timestamp, value_date) VALUES("bigquery", 1, 1.1, 1, false, TIMESTAMP(DATE "2017-09-18"), DATE '2018-01-15') 
```

task example
```
get_data = BigQueryGetDataOperator(
        task_id='get_data_from_bq',
        dataset_id=DATASET_NAME,
        table_id='dummy_table',
        max_results=100,
    )
```

Error

```
[2022-04-11, 09:50:01 UTC] {xcom.py:584} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-04-11, 09:50:01 UTC] {taskinstance.py:1766} WARNING - We expected to get frame set in local storage but it was not. Please report this as an issue with full logs at https://github.com/apache/***/issues/new
Traceback (most recent call last):
  File "/opt/airflow/airflow/models/taskinstance.py", line 1348, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/opt/airflow/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/opt/airflow/airflow/models/taskinstance.py", line 1562, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result, session=session)
  File "/opt/airflow/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/models/taskinstance.py", line 2273, in xcom_push
    XCom.set(
  File "/opt/airflow/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/models/xcom.py", line 191, in set
    value = cls.serialize_value(
  File "/opt/airflow/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
```
```

**Comment by pankajastro** [comment]
PR: https://github.com/apache/airflow/pull/22936
