### ISSUE TITLE
Bad data leading to confusing logging in SnowflakeOperatorAsync

### ISSUE THREAD

**Issue by jschenz-chwy** [astronomer/astronomer-providers#1335]
**Describe the bug**
**Given**: 
  - A dag running SQL via `SnowflakeOperatorAsync`
 
**When**: 
  - The SQL creates objects using `object_agg`, 
  - and there are duplicate keys (which is an error condition), 

**Then**: 
  - I get an inscrutable message in the logs from `SnowflakeOperatorAsync` that reads as follows:
```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/astronomer/providers/snowflake/operators/snowflake.py", line 242, in execute_complete
    msg = f"sfquid: {event['query_id']}, {event['type']}: {event['message']}"
KeyError: 'query_id'
```

This is in contrast with the `SnowflakeOperator` which provides the following message in the logs for the exact same query:

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 260, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100103 (22000): 01af51da-0608-5852-0000-a02d609fd7b2: Duplicate field key 'TABLE_CATALOG'
```

**To Reproduce**
Here is a self-contained dag to replicate the situation that I am seeing:
```
from pendulum import datetime

from airflow.decorators import dag
from astronomer.providers.snowflake.operators.snowflake import SnowflakeOperatorAsync


@dag(
    schedule=None,
    start_date=datetime(2023, 5, 1),
    catchup=False,
    tags=["snowflake", "failure", "example"],
    default_args={},
)
def failing_query():

    failure = SnowflakeOperatorAsync(
        task_id="this-query-will-fail",
        sql="""
            with duplicate_records as (
                select 
                    table_name
                    , column_name
                    , ordinal_position
                from information_schema.columns
                where table_schema = 'INFORMATION_SCHEMA'
                union all
                select 
                    table_name
                    , column_name
                    , ordinal_position
                from information_schema.columns
                where table_schema = 'INFORMATION_SCHEMA'
            )

            , query_that_cant_handle_dupes as (
                select table_name
                    , object_agg(
                        column_name, ordinal_position
                    )
                from duplicate_records
                group by all
            )
            select * from query_that_cant_handle_dupes
            """
    )

    failure

failing_query()

```

**Expected behavior**
I would like to see a message that points to the error coming from Snowflake in a more clear way, as happens with the `SnowflakeOperator`.  In this case: `snowflake.connector.errors.ProgrammingError: 100103 (22000): 01af51da-0608-5852-0000-a02d609fd7b2: Duplicate field key 'TABLE_CATALOG'`

**Additional context**
Airflow 2.5.2
astronomer-providers==1.17.3
python 3.10

Per @pankajastro this snippet is part of the problem for this issue: https://github.com/astronomer/astronomer-providers/blob/1.17.3/astronomer/providers/snowflake/triggers/snowflake_trigger.py#L65-L80

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
