### ISSUE TITLE
CNCF KubernetesPodOperatorAsync is failing in staging Env

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#160]
KubernetesPodOperatorAsync is failing with 403 error in staging Env
```
[2022-03-23, 18:05:17 UTC] {standard_task_runner.py:89} ERROR - Failed to execute job 2120 for task create_k8s_pod
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 76, in execute_complete
    self.raise_for_trigger_status(event)
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 39, in raise_for_trigger_status
    raise AirflowException(description)
airflow.exceptions.AirflowException: Trigger WaitContainerTrigger failed with exception ApiException.
trigger traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/cncf/kubernetes/triggers/wait_container.py", line 104, in run
    state = await self.wait_for_pod_start(v1_api)
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/cncf/kubernetes/triggers/wait_container.py", line 84, in wait_for_pod_start
    pod = await v1_api.read_namespaced_pod(self.pod_name, self.pod_namespace)
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/client/api_client.py", line 192, in __call_api
    raise e
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/client/api_client.py", line 185, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/client/rest.py", line 186, in GET
    return (await self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/client/rest.py", line 180, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: <CIMultiDictProxy('Audit-Id': '9f51472e-b732-431c-a91b-bc0c65de2e8c', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '330a09ef-cc74-405a-9ec4-c71bb9aa634b', 'X-Kubernetes-Pf-Prioritylevel-Uid': '8cb306f1-599c-444c-8af1-a3136a2edbd9', 'Date': 'Wed, 23 Mar 2022 18:05:14 GMT', 'Content-Length': '483')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"astro-k8s-test-pod.b828ddec6d684ee1b4d47722248bc729\" is forbidden: User \"system:serviceaccount:astronomer-cometary-asterism-3668:cometary-asterism-3668-airflow-triggerer\" cannot get resource \"pods\" in API group \"\" in the namespace \"astronomer-cometary-asterism-3668\"","reason":"Forbidden","details":{"name":"astro-k8s-test-pod.b828ddec6d684ee1b4d47722248bc729","kind":"pods"},"code":403}



```

**Comment by pankajastro** [comment]
Spend some time with Jed to debug this. Look like we have an old version of the helm chart on staging env. So as the next step we shall upgrade the staging env with an updated helm chart.

**Comment by pankajkoti** [comment]
@pankajastro Probably we can close this issue now as it works fine on Astro cloud.

**Comment by pankajastro** [comment]
> 

hmm, we can close it, regarding updating staging Viswash has recommended to use dev or QA cluster

**Comment by pankajkoti** [comment]
Okay, we have disabled master DAG run on `staging`. And since it runs fine on Astro cloud, I believe it is an infra issue on `staging` and no changes need to be done on the code. So, I will close the issue now.
cc: @phanikumv
