### ISSUE TITLE
[SPIKE/RESEARCH] Async `HivePartitionSensor`

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#208]
Research options on how to create an Async version of HivePartitionSensor:

Acceptance Criteria:
Document possible options and selection reasons for a particular library in this GitHub issue via a Summary comment.
Find a Python library that supports async implementation for the implementation if the official library does not support it.

**Comment by rajaths010494** [comment]
```
hannel 1: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
debug1: channel 1: free: direct-tcpip: listening port 8158 for ec2-18-218-118-21.us-east-2.compute.amazonaws.com port 9083, connect from 127.0.0.1 port 34606 to 127.0.0.1 port 8158, nchannels 3
debug1: channel 2: free: direct-tcpip: listening port 8158 for ec2-18-218-118-21.us-east-2.compute.amazonaws.com port 9083, connect from 127.0.0.1 port 34608 to 127.0.0.1 port 8158, nchannels 2
```

facing issue with ssh to port forward to metastore 9083 port from docker worker node


`[2022-04-11, 17:53:12 ] {standard_task_runner.py:77} INFO - Job 12: Subtask hive_partition_check
[2022-04-11, 17:53:12 ] {logging_mixin.py:109} INFO - Running <TaskInstance: example_hive_dag.hive_partition_check manual__2022-04-11T12:23:11.072146+00:00 [running]> on host 05cd5c7b2791
[2022-04-11, 17:53:12 ] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_hive_dag
AIRFLOW_CTX_TASK_ID=hive_partition_check
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T12:23:11.072146+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T12:23:11.072146+00:00
[2022-04-11, 17:53:12 ] {hive_partition.py:73} INFO - Poking for table default.zipcodes, partition state
[2022-04-11, 17:53:12 ] {base.py:70} INFO - Using connection to: id: metastore_default. Host: 127.0.0.1, Port: 8158, Schema: default, Login: hive, Password: ***, extra: {}
[2022-04-11, 17:53:12 ] {hive.py:531} INFO - Trying to connect to 127.0.0.1:8158
[2022-04-11, 17:53:12 ] {hive.py:533} INFO - Connected to 127.0.0.1:8158
[2022-04-11, 17:53:12 ] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/thrift/transport/TSocket.py", line 150, in read
    buff = self.handle.recv(sz)
ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by rajaths010494** [comment]
```
[2022-04-12, 18:42:17 ] {logging_mixin.py:109} INFO - {'logger': <Logger astronomer.providers.apache.hive.hooks.hmsclient (DEBUG)>, '_iprot': <thrift.protocol.TBinaryProtocol.TBinaryProtocol object at 0x402b3b38b0>, '_oprot': <thrift.protocol.TBinaryProtocol.TBinaryProtocol object at 0x402b3b38b0>, '_seqid': 0, '_HMSClient__isOpened': True}
[2022-04-12, 18:42:18 ] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/sensors/base.py", line 236, in execute
    while not self.poke(context):
  File "/usr/local/airflow/astronomer_providers/astronomer/providers/apache/hive/sensors/hive.py", line 76, in poke
    return hook.check_for_partition(self.schema, self.table, self.partition)
  File "/usr/local/airflow/astronomer_providers/astronomer/providers/apache/hive/hooks/hive.py", line 564, in check_for_partition
    partitions = client.get_partitions_by_filter(
  File "/usr/local/lib/python3.9/site-packages/hmsclient/genthrift/hive_metastore/ThriftHiveMetastore.py", line 3611, in get_partitions_by_filter
    return self.recv_get_partitions_by_filter()
  File "/usr/local/lib/python3.9/site-packages/hmsclient/genthrift/hive_metastore/ThriftHiveMetastore.py", line 3626, in recv_get_partitions_by_filter
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.9/site-packages/thrift/protocol/TBinaryProtocol.py", line 148, in readMessageBegin
    name = self.trans.readAll(sz)
  File "/usr/local/lib/python3.9/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.9/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/usr/local/lib/python3.9/site-packages/thrift/transport/TSocket.py", line 166, in read
    raise TTransportException(type=TTransportException.END_OF_FILE,
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```


SSH connection got established but when i ran example dag started facing above issue.
Added authMechansim none and NOSASL 
Tried with host and port  and also with enabled log level to debug as kaxil suggested. 
It was throwing the same error in the logs.
Tired different connection types for hive with Hive client wrapper , metastore and hiveserver2 same issue persisting.

**Comment by rajaths010494** [comment]
The local hive installed in the airflow docker is working. Able to connect and check for partitions exists or not.
Unable to run the same on the EMR cluster (Hive).
I will start the development with a local setup and phani is looking at resolving the remote setup.

**Comment by rajaths010494** [comment]
After we used the same hive library on the airflow image we were able to have an SSH connection to the remote EMR cluster and successfully run the sync hive partition sensor.

**Comment by phanikumv** [comment]
used impyla library to implement HivePartitionSensor as pyhive is no longer supported
