### ISSUE TITLE
LivyOperator Example DAG is broken

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#238]
```
Broken DAG: [/usr/local/airflow/dags/example_livy.py] Traceback (most recent call last):
  File "/usr/local/airflow/dags/example_livy.py", line 30, in <module>
    PRIVATE_KEY = Variable.get("providers_team_keypair")
  File "/usr/local/lib/python3.9/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable providers_team_keypair does not exist'

```

**Comment by phanikumv** [comment]
Not an issue, as the required variable is not created before the operator is executed.
