### ISSUE TITLE
Fix Redshift example DAG

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#279]
1.Replace `create_redshift_cluster` in the example DAG with the CreateRedshiftClusterOperator

2.I see the `delete_redshift_cluster_snapshot` task of the DAG has always raised an Exception on a daily basis but we're catching that in the code and as a result the task is getting marked success. Below is the exception,

```
[2022-04-25, 15:07:59 IST] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): delete_redshift_cluster_snapshot> on 2022-04-25 09:32:12.843775+00:00
[2022-04-25, 15:07:59 IST] {standard_task_runner.py:52} INFO - Started process 71 to run task
[2022-04-25, 15:07:59 IST] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_async_redshift_cluster_management', 'delete_redshift_cluster_snapshot', 'manual__2022-04-25T09:32:12.843775+00:00', '--job-id', '7687', '--raw', '--subdir', 'DAGS_FOLDER/example_redshift_cluster_management.py', '--cfg-path', '/tmp/tmpxk89w10_', '--error-file', '/tmp/tmpxopbepnn']
[2022-04-25, 15:07:59 IST] {standard_task_runner.py:80} INFO - Job 7687: Subtask delete_redshift_cluster_snapshot
[2022-04-25, 15:07:59 IST] {logging_mixin.py:109} INFO - Running <TaskInstance: example_async_redshift_cluster_management.delete_redshift_cluster_snapshot manual__2022-04-25T09:32:12.843775+00:00 [running]> on host cometary-asterism-3668-worker-c49bfd594-pfmbv
[2022-04-25, 15:07:59 IST] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_async_redshift_cluster_management
AIRFLOW_CTX_TASK_ID=delete_redshift_cluster_snapshot
AIRFLOW_CTX_EXECUTION_DATE=2022-04-25T09:32:12.843775+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-25T09:32:12.843775+00:00
[2022-04-25, 15:07:59 IST] {credentials.py:1111} INFO - Found credentials in environment variables.
[2022-04-25, 15:07:59 IST] {example_redshift_cluster_management.py:129} ERROR - Error when deleting the cluster
Traceback (most recent call last):
  File "/usr/local/airflow/dags/example_redshift_cluster_management.py", line 120, in delete_redshift_cluster_snapshot
    if get_snapshot_status() == "deleting":
  File "/usr/local/airflow/dags/example_redshift_cluster_management.py", line 55, in get_snapshot_status
    response = client.describe_cluster_snapshots(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ClusterSnapshotNotFoundFault: An error occurred (ClusterSnapshotNotFound) when calling the DescribeClusterSnapshots operation: Snapshot astro-providers-cluster-snapshot not found.
[2022-04-25, 15:07:59 IST] {python.py:175} INFO - Done. Returned value was: None
[2022-04-25, 15:07:59 IST] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=example_async_redshift_cluster_management, task_id=delete_redshift_cluster_snapshot, execution_date=20220425T093212, start_date=20220425T093759, end_date=20220425T093759
[2022-04-25, 15:07:59 IST] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25, 15:07:59 IST] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
```

We need to fix these by reraising exceptions in the below PythonOperator tasks:
`delete_redshift_cluster_snapshot`
`delete_redshift_cluster`

Additionally, debug and investigate the below error observed intermittently in the `pause_cluster_task` & `resume_cluster_task`:

```
[2022-04-25, 15:07:58 IST] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_async_redshift_cluster_management', 'pause_redshift_cluster', 'manual__2022-04-25T09:32:12.843775+00:00', '--job-id', '7686', '--raw', '--subdir', 'DAGS_FOLDER/example_redshift_cluster_management.py', '--cfg-path', '/tmp/tmpwf85jajm', '--error-file', '/tmp/tmp86pagb7_']
[2022-04-25, 15:07:58 IST] {standard_task_runner.py:80} INFO - Job 7686: Subtask pause_redshift_cluster
[2022-04-25, 15:07:58 IST] {standard_task_runner.py:52} INFO - Started process 69 to run task
[2022-04-25, 15:07:58 IST] {logging_mixin.py:109} INFO - Running <TaskInstance: example_async_redshift_cluster_management.pause_redshift_cluster manual__2022-04-25T09:32:12.843775+00:00 [running]> on host cometary-asterism-3668-worker-c49bfd594-pfmbv
[2022-04-25, 15:07:58 IST] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_async_redshift_cluster_management
AIRFLOW_CTX_TASK_ID=pause_redshift_cluster
AIRFLOW_CTX_EXECUTION_DATE=2022-04-25T09:32:12.843775+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-25T09:32:12.843775+00:00
[2022-04-25, 15:07:58 IST] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/amazon/aws/operators/redshift_cluster.py", line 140, in execute_complete
    raise AirflowException(msg)
airflow.exceptions.AirflowException: error: An error occurred (InvalidClusterState) when calling the PauseCluster operation: There is an operation running on the Cluster. Please try to pause it at a later time.
[2022-04-25, 15:07:58 IST] {taskinstance.py:1278} INFO - Marking task as FAILED. dag_id=example_async_redshift_cluster_management, task_id=pause_redshift_cluster, execution_date=20220425T093212, start_date=20220425T093758, end_date=20220425T093758
```

**Comment by phanikumv** [comment]
The delete cluster task shouldnt raise the below exception after cluster is deleted

`[2022-05-13, 06:41:32 UTC] {example_redshift_sql.py:41} INFO - {'Clusters': [{'ClusterIdentifier': 'astro-providers-cluster', 'NodeType': 'dc2.large', 'ClusterStatus': 'deleting', 'ClusterAvailabilityStatus': 'Modifying', 'MasterUsername': 'awsuser', 'DBName': 'astro_dev', 'Endpoint': {'Port': 5439}, 'ClusterCreateTime': datetime.datetime(2022, 5, 13, 6, 40, 5, 36000, tzinfo=tzlocal()), 'AutomatedSnapshotRetentionPeriod': 1, 'ManualSnapshotRetentionPeriod': -1, 'ClusterSecurityGroups': [], 'VpcSecurityGroups': [{'VpcSecurityGroupId': 'sg-0029c26643ae706e4', 'Status': 'active'}], 'ClusterParameterGroups': [{'ParameterGroupName': 'default.redshift-1.0', 'ParameterApplyStatus': 'in-sync'}], 'ClusterSubnetGroupName': 'default', 'VpcId': 'vpc-0166dd2b1bbd06a95', 'AvailabilityZone': 'us-east-2a', 'PreferredMaintenanceWindow': 'sat:06:00-sat:06:30', 'PendingModifiedValues': {}, 'ClusterVersion': '1.0', 'AllowVersionUpgrade': True, 'NumberOfNodes': 1, 'PubliclyAccessible': True, 'Encrypted': False, 'ClusterPublicKey': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCabygBloIlXXWmOj/pm0SYvk8Deqil2DNddJEm2oeZR8N8i8a2x66tN5YOfQM4tYCOvtXm5+1GZUtWRqtErNs1l7HH2Mb16u80J6/AT+EbhqndbP/zUbu5rfDpmuBummrC0AkEeO2s8Cz0r8yMsOMEzT3KlwxfT9HTnfXPUjY4TjHqNu5s+6JrrvVz3GacMT55VulJT6XgX9Kp/nielPi5g9lGastwQVEq68AjPa69jvQ1INfJYAUw1U9a5x8mvl8VcKvPQ8Z9ID1lAEN9mDD8i3K69FifHt4a/5m2VjOlqvfG/FOBnfwUmgGNqaax/jbTbmBKJR4BqQTwe4m+ouLZ Amazon-Redshift\n', 'ClusterNodes': [{'NodeRole': 'SHARED', 'PrivateIPAddress': '172.31.3.110', 'PublicIPAddress': '18.220.143.75'}], 'ClusterRevisionNumber': '38112', 'Tags': [{'Key': 'Purpose', 'Value': 'ProviderTest'}], 'EnhancedVpcRouting': False, 'IamRoles': [], 'MaintenanceTrackName': 'current', 'DeferredMaintenanceWindows': [], 'NextMaintenanceWindowStartTime': datetime.datetime(2022, 5, 14, 6, 0, tzinfo=tzlocal()), 'AvailabilityZoneRelocationStatus': 'disabled', 'ClusterNamespaceArn': 'arn:aws:redshift:us-east-2:396807896376:namespace:64c2d14c-db48-48eb-ae5d-9ce3f152488b', 'AquaConfiguration': {'AquaStatus': 'disabled', 'AquaConfigurationStatus': 'auto'}}], 'ResponseMetadata': {'RequestId': '56e32073-54da-466f-aef6-bcb23771cae9', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '56e32073-54da-466f-aef6-bcb23771cae9', 'content-type': 'text/xml', 'content-length': '3749', 'vary': 'accept-encoding', 'date': 'Fri, 13 May 2022 06:41:31 GMT'}, 'RetryAttempts': 0}}
[2022-05-13, 06:42:02 UTC] {example_redshift_sql.py:41} INFO - {'Clusters': [{'ClusterIdentifier': 'astro-providers-cluster', 'NodeType': 'dc2.large', 'ClusterStatus': 'deleting', 'ClusterAvailabilityStatus': 'Modifying', 'MasterUsername': 'awsuser', 'DBName': 'astro_dev', 'Endpoint': {'Port': 5439}, 'ClusterCreateTime': datetime.datetime(2022, 5, 13, 6, 40, 5, 36000, tzinfo=tzlocal()), 'AutomatedSnapshotRetentionPeriod': 1, 'ManualSnapshotRetentionPeriod': -1, 'ClusterSecurityGroups': [], 'VpcSecurityGroups': [{'VpcSecurityGroupId': 'sg-0029c26643ae706e4', 'Status': 'active'}], 'ClusterParameterGroups': [{'ParameterGroupName': 'default.redshift-1.0', 'ParameterApplyStatus': 'in-sync'}], 'ClusterSubnetGroupName': 'default', 'VpcId': 'vpc-0166dd2b1bbd06a95', 'AvailabilityZone': 'us-east-2a', 'PreferredMaintenanceWindow': 'sat:06:00-sat:06:30', 'PendingModifiedValues': {}, 'ClusterVersion': '1.0', 'AllowVersionUpgrade': True, 'NumberOfNodes': 1, 'PubliclyAccessible': True, 'Encrypted': False, 'ClusterPublicKey': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCabygBloIlXXWmOj/pm0SYvk8Deqil2DNddJEm2oeZR8N8i8a2x66tN5YOfQM4tYCOvtXm5+1GZUtWRqtErNs1l7HH2Mb16u80J6/AT+EbhqndbP/zUbu5rfDpmuBummrC0AkEeO2s8Cz0r8yMsOMEzT3KlwxfT9HTnfXPUjY4TjHqNu5s+6JrrvVz3GacMT55VulJT6XgX9Kp/nielPi5g9lGastwQVEq68AjPa69jvQ1INfJYAUw1U9a5x8mvl8VcKvPQ8Z9ID1lAEN9mDD8i3K69FifHt4a/5m2VjOlqvfG/FOBnfwUmgGNqaax/jbTbmBKJR4BqQTwe4m+ouLZ Amazon-Redshift\n', 'ClusterNodes': [{'NodeRole': 'SHARED', 'PublicIPAddress': '18.220.143.75'}], 'ClusterRevisionNumber': '38112', 'Tags': [], 'EnhancedVpcRouting': False, 'IamRoles': [], 'MaintenanceTrackName': 'current', 'DeferredMaintenanceWindows': [], 'NextMaintenanceWindowStartTime': datetime.datetime(2022, 5, 14, 6, 0, tzinfo=tzlocal()), 'AvailabilityZoneRelocationStatus': 'disabled', 'ClusterNamespaceArn': 'arn:aws:redshift:us-east-2:396807896376:namespace:64c2d14c-db48-48eb-ae5d-9ce3f152488b', 'AquaConfiguration': {'AquaStatus': 'disabled', 'AquaConfigurationStatus': 'auto'}}], 'ResponseMetadata': {'RequestId': 'b998ed64-651f-44a1-a964-c4df601f7655', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'b998ed64-651f-44a1-a964-c4df601f7655', 'content-type': 'text/xml', 'content-length': '3568', 'vary': 'accept-encoding', 'date': 'Fri, 13 May 2022 06:42:02 GMT'}, 'RetryAttempts': 0}}
[2022-05-13, 06:42:32 UTC] {example_redshift_sql.py:62} ERROR - Error deleting redshift cluster
Traceback (most recent call last):
  File "/usr/local/airflow/dags/example_redshift_sql.py", line 58, in delete_redshift_cluster
    if get_cluster_status() == "deleting":
  File "/usr/local/airflow/dags/example_redshift_sql.py", line 38, in get_cluster_status
    response = client.describe_clusters(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ClusterNotFoundFault: An error occurred (ClusterNotFound) when calling the DescribeClusters operation: Cluster astro-providers-cluster not found.
[2022-05-13, 06:42:32 UTC] {taskinstance.py:1888} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/example_redshift_sql.py", line 63, in delete_redshift_cluster
    raise exception
  File "/usr/local/airflow/dags/example_redshift_sql.py", line 58, in delete_redshift_cluster
    if get_cluster_status() == "deleting":
  File "/usr/local/airflow/dags/example_redshift_sql.py", line 38, in get_cluster_status
    response = client.describe_clusters(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ClusterNotFoundFault: An error occurred (ClusterNotFound) when calling the DescribeClusters operation: Cluster astro-providers-cluster not found.`
