### ISSUE TITLE
Solution to detect classpath issues in serialize method of Async Trigger

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#30]
We need a solution to highlight to the developer whenever an incorrect trigger classpath is used in the serialize method.

We ended up spending unreasonable time to detect this last time, as the task will just show the exception as "Trigger failure" and no other information

Either write a unit test to detect this (or) come up with an alternative approach.

**Comment by rajaths010494** [comment]
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/***/utils/module_loading.py", line 35, in import_string
    return getattr(module, class_name)

AttributeError: module 'astronomer.providers.microsoft.azure.triggers.data_factory' has no attribute 'WasbToSynpaseTrigger'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/***/jobs/triggerer_job.py", line 406, in update_triggers
    trigger_class = self.get_trigger_by_classpath(new_triggers[new_id].classpath)

  File "/usr/local/lib/python3.9/site-packages/***/jobs/triggerer_job.py", line 423, in get_trigger_by_classpath
    self.trigger_cache[classpath] = import_string(classpath)

  File "/usr/local/lib/python3.9/site-packages/***/utils/module_loading.py", line 37, in import_string
    raise ImportError(f'Module "{module_path}" does not define a "{class_name}" attribute/class')

ImportError: Module "astronomer.providers.microsoft.azure.triggers.data_factory" does not define a "WasbToSynpaseTrigger" attribute/class

**Comment by rajaths010494** [comment]
in airflow trigger now sends the error message with import error mentioned in the above comment,
