### ISSUE TITLE
Redshift cluster management DAG delete cluster task failing

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#355]
Seeing this error 
```
option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-05-17, 00:19:59 UTC] {task_command.py:369} INFO - Running <TaskInstance: example_async_redshift_cluster_management.delete_redshift_cluster redshift_cluster_mgmt_dag_example_async_redshift_cluster_management_2022-05-16 [running]> on host 10.1.2.243
[2022-05-17, 00:20:00 UTC] {taskinstance.py:1568} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_async_redshift_cluster_management
AIRFLOW_CTX_TASK_ID=delete_redshift_cluster
AIRFLOW_CTX_EXECUTION_DATE=2022-05-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=redshift_cluster_mgmt_dag_example_async_redshift_cluster_management_2022-05-16
[2022-05-17, 00:20:00 UTC] {credentials.py:1111} INFO - Found credentials in environment variables.
[2022-05-17, 00:20:00 UTC] {example_redshift_cluster_management.py:171} ERROR - Error deleting redshift cluster
Traceback (most recent call last):
  File "/usr/local/airflow/dags/example_redshift_cluster_management.py", line 155, in delete_redshift_cluster_callable
    client.delete_cluster(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidClusterStateFault: An error occurred (InvalidClusterState) when calling the DeleteCluster operation: There is an operation running on the Cluster. Please try to delete it at a later time.
[2022-05-17, 00:20:00 UTC] {taskinstance.py:1888} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/example_redshift_cluster_management.py", line 155, in delete_redshift_cluster_callable
    client.delete_cluster(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidClusterStateFault: An error occurred (InvalidClusterState) when calling the DeleteCluster operation: There is an operation running on the Cluster. Please try to delete it at a later time.
```

**Comment by phanikumv** [comment]
Closing as this issue is not occurring now
