### ISSUE TITLE
CreateRedshifClusterOperator failing for single-node cluster

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#376]
```
[2022-05-23, 09:42:24 UTC] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-05-23, 09:42:24 UTC] {base_aws.py:100} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-05-23, 09:42:25 UTC] {taskinstance.py:1827} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/airflow/providers/amazon/aws/operators/redshift_cluster.py", line 239, in execute
    params,
  File "/opt/airflow/airflow/providers/amazon/aws/hooks/redshift_cluster.py", line 74, in create_cluster
    raise e
  File "/opt/airflow/airflow/providers/amazon/aws/hooks/redshift_cluster.py", line 70, in create_cluster
    **params,
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 911, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateCluster operation: Number of nodes must be not be supplied for cluster type single-node.
[2022-05-23, 09:42:25 UTC] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=example_redshift, task_id=redshift_create_cluster, execution_date=20220523T094220, start_date=20220523T094223, end_date=20220523T094225
[2022-05-23, 09:42:25 UTC] {standard_task_runner.py:102} ERROR - Failed to execute job 10 for task redshift_create_cluster (An error occurred (InvalidParameterValue) when calling the CreateCluster operation: Number of nodes must be not be supplied for cluster type single-node.; 255)
```

**Comment by pankajastro** [comment]
https://github.com/apache/airflow/pull/23839
