### ISSUE TITLE
Add GKEStartPodOperatorAsync Example DAG

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#390]
Add GKEStartPodOperatorAsync Example DAG for integration testing

**Comment by pankajastro** [comment]
Draft PR: https://github.com/astronomer/astronomer-providers/pull/385

**Comment by pankajastro** [comment]
Look like our team GCP project does not have permission for Kubernetes Engine API

**Comment by pankajastro** [comment]
The above issue has been resolved. I'm able to run `GKECreateClusterOperator` and `GKEDeleteClusterOperator` but `GKEStartPodOperatorAsync` failing on astro-cloud with below error

```
[2022-05-26, 14:33:42 UTC] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/google/cloud/operators/kubernetes_engine.py", line 90, in execute
    with GKEStartPodOperator.get_gke_config_file(
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/kubernetes_engine.py", line 364, in get_gke_config_file
    with tempfile.NamedTemporaryFile() as conf_file, patch_environ(
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 513, in provide_authorized_gcloud
    check_output(
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcloud' 
```

**Comment by pankajastro** [comment]
> The above issue has been resolved. I'm able to run `GKECreateClusterOperator` and `GKEDeleteClusterOperator` but `GKEStartPodOperatorAsync` failing on astro-cloud with below error
> 
> ```
> [2022-05-26, 14:33:42 UTC] {taskinstance.py:1890} ERROR - Task failed with exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/astronomer/providers/google/cloud/operators/kubernetes_engine.py", line 90, in execute
>     with GKEStartPodOperator.get_gke_config_file(
>   File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
>     return next(self.gen)
>   File "/usr/local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/kubernetes_engine.py", line 364, in get_gke_config_file
>     with tempfile.NamedTemporaryFile() as conf_file, patch_environ(
>   File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
>     return next(self.gen)
>   File "/usr/local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 513, in provide_authorized_gcloud
>     check_output(
>   File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/local/lib/python3.9/subprocess.py", line 505, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'gcloud' 
> ```

After Installing GCP cli in the container this issue has been resolved

**Comment by pankajastro** [comment]
Namespace is always `exact-cluster-1733` which equivalent to astro-cloud namespace and getting below error
```
[2022-05-26, 19:24:12 UTC] {kubernetes_pod.py:541} INFO - Creating pod astro-k8s-gke-test-pod-3130b0cbb16045b586949748829430fb with labels: {'dag_id': 'example_google_kubernetes_engine', 'task_id': 'start_pod', 'run_id': 'manual__2022-05-26T192032.3291750000-cf6ea9ab9', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2022-05-26, 19:24:12 UTC] {warnings.py:109} WARNING - /usr/local/airflow/airflow_local_settings.py:94: DeprecationWarning: Accessing configuration method 'get' directly from the configuration module is deprecated. Please access the configuration from the 'configuration.conf' object via 'conf.get'
  pod.metadata.namespace = conf.get("kubernetes", "NAMESPACE")

[2022-05-26, 19:24:13 UTC] {pod_manager.py:137} ERROR - Exception when attempting to create Namespaced Pod: {   "apiVersion": "v1",   "kind": "Pod",   "metadata": {     "annotations": {},     "labels": {       "dag_id": "example_google_kubernetes_engine",       "task_id": "start_pod",       "run_id": "manual__2022-05-26T192032.3291750000-cf6ea9ab9",       "kubernetes_pod_operator": "True",       "try_number": "1",       "airflow_version": "2.3.1-astro.1"     },     "name": "astro-k8s-gke-test-pod-3130b0cbb16045b586949748829430fb",     "namespace": "exact-cluster-1733"   },   "spec": {     "affinity": {},     "containers": [       {         "args": [],         "command": [],         "env": [],         "envFrom": [],         "image": "ubuntu",         "name": "base",         "ports": [],         "resources": {},         "volumeMounts": []       }     ],     "hostNetwork": false,     "imagePullSecrets": [],     "initContainers": [],     "nodeSelector": {},     "restartPolicy": "Never",     "securityContext": {},     "serviceAccountName": "exact-cluster-1733-kpo",     "tolerations": [],     "volumes": []   } }
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 132, in run_pod_async
    resp = self._client.create_namespaced_pod(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 7356, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 7455, in create_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 275, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'aa31e3d7-d81d-4b8a-889c-4903e6adb3b4', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'cc4c0c48-db13-46ec-8e91-13c05ded267b', 'X-Kubernetes-Pf-Prioritylevel-Uid': '5449ec97-786e-415b-9635-e08cd9f62397', 'Date': 'Thu, 26 May 2022 19:24:13 GMT', 'Content-Length': '216'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"exact-cluster-1733\" not found","reason":"NotFound","details":{"name":"exact-cluster-1733","kind":"namespaces"},"code":404}
```

**Comment by pankajastro** [comment]
Even on my local setup failing 
```
[2022-05-26, 20:52:28 UTC] {task_command.py:370} INFO - Running <TaskInstance: example_google_kubernetes_engine.start_pod manual__2022-05-26T20:48:18.415528+00:00 [running]> on host 858ab7834dce
[2022-05-26, 20:52:28 UTC] {kubernetes_pod.py:541} INFO - Creating pod astro-k8s-gke-test-pod-4e5b5968854741d483fd9e1b56de9e0a with labels: {'dag_id': 'example_google_kubernetes_engine', 'task_id': 'start_pod', 'run_id': 'manual__2022-05-26T204818.4155280000-2536010c8', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2022-05-26, 20:52:28 UTC] {kubernetes_pod.py:434} INFO - Deleting pod: astro-k8s-gke-test-pod-4e5b5968854741d483fd9e1b56de9e0a
[2022-05-26, 20:52:28 UTC] {kubernetes_pod.py:586} ERROR - Invalid kube-config file. No configuration found.
Traceback (most recent call last):
  File "/usr/local/airflow/astronomer_providers/astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 105, in trigger_reentry
    self.pod = self.find_pod(
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 336, in find_pod
    pod_list = self.client.list_namespaced_pod(
  File "/usr/local/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 331, in client
    return kube_client.get_kube_client(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/kubernetes/kube_client.py", line 113, in get_kube_client
    config.load_kube_config(config_file=config_file, context=cluster_context)
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 808, in load_kube_config
    loader = _get_kube_config_loader(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 767, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

During handling of the above exception, another exception occurred:

```

**Comment by pankajastro** [comment]
Able to run sync version i.e `GKEStartPodOperator`  on local 
```
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-26T20:55:34.090111+00:00
[2022-05-26, 20:58:52 UTC] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-05-26, 20:59:04 UTC] {process_utils.py:165} INFO - Executing cmd: gcloud container clusters get-credentials provider-team-gke-cluster --project astronomer-***-providers --zone us-west1
[2022-05-26, 20:59:04 UTC] {process_utils.py:169} INFO - Output:
[2022-05-26, 20:59:08 UTC] {process_utils.py:173} INFO - WARNING: Accessing a Kubernetes Engine cluster requires the kubernetes commandline
[2022-05-26, 20:59:08 UTC] {process_utils.py:173} INFO - client [kubectl]. To install, run
[2022-05-26, 20:59:08 UTC] {process_utils.py:173} INFO -   $ gcloud components install kubectl
[2022-05-26, 20:59:08 UTC] {process_utils.py:173} INFO - 
[2022-05-26, 20:59:08 UTC] {process_utils.py:173} INFO - Fetching cluster endpoint and auth data.
[2022-05-26, 20:59:09 UTC] {process_utils.py:173} INFO - kubeconfig entry generated for provider-team-gke-cluster.
[2022-05-26, 20:59:09 UTC] {kubernetes_pod.py:541} INFO - Creating pod astro-k8s-gke-test-pod-7da29c9291884e418f126985bb69a6bd with labels: {'dag_id': 'example_google_kubernetes_engine', 'task_id': 'start_pod', 'run_id': 'manual__2022-05-26T205534.0901110000-eb1f07d8c', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2022-05-26, 20:59:16 UTC] {pod_manager.py:178} WARNING - Pod not yet started: astro-k8s-gke-test-pod-7da29c9291884e418f126985bb69a6bd
[2022-05-26, 20:59:18 UTC] {pod_manager.py:178} WARNING - Pod not yet started: astro-k8s-gke-test-pod-7da29c9291884e418f126985bb69a6bd
[2022-05-26, 20:59:19 UTC] {pod_manager.py:178} WARNING - Pod not yet started: astro-k8s-gke-test-pod-7da29c9291884e418f126985bb69a6bd
[2022-05-26, 20:59:20 UTC] {pod_manager.py:178} WARNING - Pod not yet started: astro-k8s-gke-test-pod-7da29c9291884e418f126985bb69a6bd
[2022-05-26, 20:59:23 UTC] {kubernetes_pod.py:437} INFO - skipping deleting pod: astro-k8s-gke-test-pod-7da29c9291884e418f126985bb69a6bd
[2022-05-26, 20:59:23 UTC] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=example_google_kubernetes_engine, task_id=start_pod, execution_date=20220526T205534, start_date=20220526T205851, end_date=20220526T205923
[2022-05-26, 20:59:23 UTC] {manager.py:53} WARNING - Unable to find an extractor. task_type=GKEStartPodOperator ***_dag_id=example_google_kubernetes_engine task_id=start_pod ***_run_id=manual__2022-05-26T20:55:34.090111+00:00 
[2022-05-26, 20:59:23 UTC] {console.py:21} INFO - {"eventTime": "2022-05-26T20:59:23.408436Z", "eventType": "COMPLETE", "inputs": [], "job": {"facets": {}, "name": "example_google_kubernetes_engine.start_pod", "namespace": "default"}, "outputs": [], "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.8.2/integration/***", "run": {"facets": {"unknownSourceAttribute": {"_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.8.2/integration/***", "_schemaURL": "https://raw.githubusercontent.com/OpenLineage/OpenLineage/main/spec/OpenLineage.json#/definitions/BaseFacet", "unknownItems": [{"name": "GKEStartPodOperator", "properties": {"_BaseOperator__from_mapped": false, "_BaseOperator__init_kwargs": {"cluster_name": "provider-team-gke-cluster", "execution_timeout": "<<non-serializable: timedelta>>", "gcp_conn_id": "google_cloud_default", "image": "ubuntu", "in_cluster": false, "is_delete_operator_pod": false, "location": "us-west1", "name": "astro_k8s_gke_test_pod", "namespace": "default", "project_id": "astronomer-***-providers", "task_id": "start_pod"}, "_BaseOperator__instantiated": true, "_dag": "<<non-serializable: DAG>>", "_inlets": [], "_log": "<<non-serializable: Logger>>", "_outlets": [], "affinity": {}, "annotations": {}, "arguments": [], "cluster_name": "provider-team-gke-cluster", "cmds": [], "depends_on_past": false, "do_xcom_push": false, "downstream_task_ids": ["cluster_delete", "end"], "email_on_failure": true, "email_on_retry": true, "env_from": [], "env_vars": [], "execution_timeout": "<<non-serializable: timedelta>>", "executor_config": {}, "gcp_conn_id": "google_cloud_default", "get_logs": true, "hostnetwork": false, "ignore_first_depends_on_past": true, "image": "ubuntu", "image_pull_secrets": [], "in_cluster": false, "init_containers": [], "inlets": [], "is_delete_operator_pod": false, "k8s_resources": {}, "labels": {}, "location": "us-west1", "log_events_on_failure": false, "name": "astro-k8s-gke-test-pod", "namespace": "default", "node_selector": {}, "outlets": [], "owner": "***", "params": "<<non-serializable: ParamsDict>>", "pool": "default_pool", "pool_slots": 1, "ports": [], "priority_weight": 1, "project_id": "astronomer-***-providers", "queue": "default", "random_name_suffix": true, "reattach_on_restart": true, "regional": false, "retries": 0, "retry_delay": "<<non-serializable: timedelta>>", "retry_exponential_backoff": false, "secrets": [], "security_context": {}, "start_date": "<<non-serializable: DateTime>>", "startup_timeout_seconds": 120, "task_group": "<<non-serializable: weakproxy>>", "task_id": "start_pod", "tolerations": [], "trigger_rule": "all_success", "upstream_task_ids": ["cluster_create"], "use_internal_ip": false, "volume_mounts": [], "volumes": [], "wait_for_downstream": false, "weight_rule": "downstream"}, "type": "operator"}]}}, "runId": "b7231c30-f6f4-4447-97a3-78603d58edad"}}
[2022-05-26, 20:59:23 UTC] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-26, 20:59:23 UTC] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check

```

**Comment by pankajastro** [comment]
Look like when 2nd time it is deferring then not able to find the generated Kubernetes config file
Trigger Log. 
```
[2022-05-28 12:57:42,555] {triggerer_job.py:101} INFO - Starting the triggerer

/usr/local/lib/python3.9/site-packages/airflow/configuration.py:525 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.

[2022-05-28 12:58:24,672] {triggerer_job.py:359} INFO - Trigger <astronomer.providers.cncf.kubernetes.triggers.wait_container.WaitContainerTrigger kubernetes_conn_id=None, hook_params={'cluster_context': None, 'config_file': '/tmp/tmp4ul9l9rx', 'in_cluster': False}, pod_name=astro-k8s-gke-test-pod-ea206042c5db431ab4899ce10ead2c50, container_name=base, pod_namespace=default, pending_phase_timeout=120, poll_interval=5, logging_interval=None, last_log_time=None> (ID 7) starting

[2022-05-28 12:58:24,676] {wait_container.py:119} INFO - Checking pod 'astro-k8s-gke-test-pod-ea206042c5db431ab4899ce10ead2c50' in namespace 'default'.

[2022-05-28 12:58:24,678] {wait_container.py:83} INFO - hook param = {'cluster_context': None, 'config_file': '/tmp/tmp4ul9l9rx', 'in_cluster': False}

[2022-05-28 12:58:24,684] {kube_config.py:482} WARNING - Config not found: /tmp/tmp4ul9l9rx

[2022-05-28 12:58:24,702] {triggerer_job.py:362} INFO - Trigger <astronomer.providers.cncf.kubernetes.triggers.wait_container.WaitContainerTrigger kubernetes_conn_id=None, hook_params={'cluster_context': None, 'config_file': '/tmp/tmp4ul9l9rx', 'in_cluster': False}, pod_name=astro-k8s-gke-test-pod-ea206042c5db431ab4899ce10ead2c50, container_name=base, pod_namespace=default, pending_phase_timeout=120, poll_interval=5, logging_interval=None, last_log_time=None> (ID 7) fired: TriggerEvent<{'status': 'error', 'error_type': 'ConfigException', 'description': 'Trigger WaitContainerTrigger failed with exception ConfigException.\ntrigger exception message: Invalid kube-config file. Expected key current-context in kube-config\ntrigger traceback:\nTraceback (most recent call last):\n  File "/usr/local/airflow/astronomer_providers/astronomer/providers/cncf/kubernetes/triggers/wait_container.py", line 122, in run\n    async with await hook.get_api_client_async() as api_client:\n  File "/usr/local/airflow/astronomer_providers/astronomer/providers/cncf/kubernetes/hooks/kubernetes_async.py", line 72, in get_api_client_async\n    kube_client = await self._load_config()\n  File "/usr/local/airflow/astronomer_providers/astronomer/providers/cncf/kubernetes/hooks/kubernetes_async.py", line 45, in _load_config\n    await config.load_kube_config(\n  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/config/kube_config.py", line 566, in load_kube_config\n    loader = _get_kube_config_loader_for_yaml_file(\n  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/config/kube_config.py", line 530, in _get_kube_config_loader_for_yaml_file\n    return KubeConfigLoader(\n  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/config/kube_config.py", line 148, in __init__\n    self.set_active_context(active_context)\n  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/config/kube_config.py", line 159, in set_active_context\n    context_name = self._config[\'current-context\']\n  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/config/kube_config.py", line 415, in __getitem__\n    raise ConfigException(\nkubernetes_asyncio.config.config_exception.ConfigException: Invalid kube-config file. Expected key current-context in kube-config\n'}>
```
So maybe we will have to run this on the trigger 
```
 with GKEStartPodOperator.get_gke_config_file(
                gcp_conn_id=self.gcp_conn_id,
                project_id=self.project_id,
                cluster_name=self.cluster_name,
                impersonation_chain=self.impersonation_chain,
                regional=self.regional,
                location=self.location,
                use_internal_ip=self.use_internal_ip,
        ) as config_file:
            self.config_file  = config_file
            return super().execute(context)
```

**Comment by pankajastro** [comment]
I also checked in the container the generated Kube conf file is on the worker but not on the trigger

**Comment by raphaelauv** [comment]
@pankajastro what about that -> https://github.com/astronomer/astronomer-providers/pull/397

**Comment by pankajastro** [comment]
> @pankajastro what about that -> #397

I have added one comment please let me know what you think
