### ISSUE TITLE
Update GCP_LOCATION env to correct value

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#391]
Update GCP_LOCATION env default value to correct value in example DAG.
The current default value is us which is not correct 
https://cloud.google.com/compute/docs/regions-zones

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Location "us" does not exist."
	debug_error_string = "{"created":"@1653574528.859557170","description":"Error received from peer ipv4:172.253.122.95:443","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Location "us" does not exist.","grpc_status":3}"
>

```

**Comment by pankajkoti** [comment]
This issue seems to be a transient issue. The region `US` actually exists implicitly and the DAG runs fine with the region; this [link](https://cloud.google.com/bigquery/docs/locations#multi-regions) mentions about the region `US`. It ran fine today on the master DAG and ran fine on local in multiple attempts that I tried yesterday.
However, if I try to update the location to `us-west1` / `us-east1 `/ `us-east4` as mentioned in https://cloud.google.com/compute/docs/regions-zones , the DAG in fact is failing for the `insert_query_job` task with the below error
```
--------------------------------------------------------------------------------
[2022-06-03, 04:52:30 UTC] {taskinstance.py:1378} INFO - Executing <Task(BigQueryInsertJobOperatorAsync): insert_query_job> on 2022-06-03 04:49:27.525895+00:00
[2022-06-03, 04:52:30 UTC] {standard_task_runner.py:52} INFO - Started process 1484 to run task
[2022-06-03, 04:52:31 UTC] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_async_bigquery_queries', 'insert_query_job', 'manual__2022-06-03T04:49:27.525895+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/example_bigquery_queries.py', '--cfg-path', '/tmp/tmpqrm00fui', '--error-file', '/tmp/tmp3i91zqlr']
[2022-06-03, 04:52:31 UTC] {standard_task_runner.py:80} INFO - Job 299: Subtask insert_query_job
[2022-06-03, 04:52:31 UTC] {task_command.py:370} INFO - Running <TaskInstance: example_async_bigquery_queries.insert_query_job manual__2022-06-03T04:49:27.525895+00:00 [running]> on host 83e872cacfba
[2022-06-03, 04:52:31 UTC] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/astronomer_providers/astronomer/providers/google/cloud/operators/bigquery.py", line 132, in execute_complete
    raise AirflowException(event["message"])
airflow.exceptions.AirflowException: 404, message='Not Found: {\n  "error": {\n    "code": 404,\n    "message": "Not found: Job astronomer-***-providers:***_example_async_bigquery_queries_insert_query_job_2022_06_03T04_49_27_525895_00_00_956c3da41fbddaf1155382ad93d406ed",\n    "errors": [\n      {\n        "message": "Not found: Job astronomer-***-providers:***_example_async_bigquery_queries_insert_query_job_2022_06_03T04_49_27_525895_00_00_956c3da41fbddaf1155382ad93d406ed",\n        "domain": "global",\n        "reason": "notFound"\n      }\n    ],\n    "status": "NOT_FOUND"\n  }\n}\n', url=URL('https://www.googleapis.com/bigquery/v2/projects/astronomer-***-providers/jobs/***_example_async_bigquery_queries_insert_query_job_2022_06_03T04_49_27_525895_00_00_956c3da41fbddaf1155382ad93d406ed')
[2022-06-03, 04:52:31 UTC] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=example_async_bigquery_queries, task_id=insert_query_job, execution_date=20220603T044927, start_date=20220603T045221, end_date=20220603T045231
[2022-06-03, 04:52:31 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 299 for task insert_query_job (404, message='Not Found: {\n  "error": {\n    "code": 404,\n    "message": "Not found: Job astronomer-***-providers:***_example_async_bigquery_queries_insert_query_job_2022_06_03T04_49_27_525895_00_00_956c3da41fbddaf1155382ad93d406ed",\n    "errors": [\n      {\n        "message": "Not found: Job astronomer-***-providers:***_example_async_bigquery_queries_insert_query_job_2022_06_03T04_49_27_525895_00_00_956c3da41fbddaf1155382ad93d406ed",\n        "domain": "global",\n        "reason": "notFound"\n      }\n    ],\n    "status": "NOT_FOUND"\n  }\n}\n', url=URL('https://www.googleapis.com/bigquery/v2/projects/astronomer-***-providers/jobs/***_example_async_bigquery_queries_insert_query_job_2022_06_03T04_49_27_525895_00_00_956c3da41fbddaf1155382ad93d406ed'); 1484)
[2022-06-03, 04:52:31 UTC] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-03, 04:52:32 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

I am attaching the screenshots of the datasets successfully created with `US` location
<img width="1128" alt="Screenshot 2022-06-03 at 10 09 22 AM" src="https://user-images.githubusercontent.com/10206082/171789366-1a4f1903-b1b4-4772-a333-0131ee72b697.png">

**Comment by pankajkoti** [comment]
Closing the ticket for now based on above comments; we can reopen for further investigation if we observe the issue again.
