### ISSUE TITLE
Fix example DAG on async batch

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#413]
Fix the below task failure on the example DAG,  this is intermittent though.

botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the DeleteJobQueue operation: Cannot delete, resource is being modified
[2022-06-03, 13:36:08 UTC] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/example_batch.py", line 204, in delete_job_queue_func
    raise error
  File "/usr/local/airflow/dags/example_batch.py", line 195, in delete_job_queue_func
    client.delete_job_queue(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the DeleteJobQueue operation: Cannot delete, resource is being modified

**Comment by rajaths010494** [comment]
https://github.com/astronomer/astronomer-providers/pull/500
