### ISSUE TITLE
Fix RedshiftSQL Operator failure with latest apache-airflow-providers-amazon==4.1.0rc1

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#523]
In amazon==4.1.0rc1 AwsBaseHook requires any one `resource_type` and `client_type` if both were passed there was an value error raised 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/amazon/aws/operators/redshift_sql.py", line 39, in execute
    query_ids, response = redshift_data_hook.execute_query(sql=cast(str, self.sql), params=self.params)
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/amazon/aws/hooks/redshift_data.py", line 109, in execute_query
    client = self.get_conn()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 576, in get_conn
    return self.conn
  File "/usr/local/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 541, in conn
    raise ValueError(
ValueError: Either client_type='redshift-data' or resource_type='redshift-data' must be provided, not both.
```

**Comment by bharanidharan14** [comment]
Changes made to RedshiftDataHook and RedshiftSQLHookAsync regarding the apache-airflow-providers-amazon==4.1.0rc1 rc image version changes in this [PR](https://github.com/apache/airflow/pull/24662)

**Comment by bharanidharan14** [comment]
Changes made to RedshiftDataHook and RedshiftSQLHookAsync regarding the apache-airflow-providers-amazon==4.1.0rc1 rc image version changes in this [PR](https://github.com/apache/airflow/pull/24662)
