### ISSUE TITLE
KPOA -> is not using kube_config_path or kube_config (JSON) from kubernetes connection

### ISSUE THREAD

**Issue by raphaelauv** [astronomer/astronomer-providers#745]
**Describe the bug**

I have this error with the KPOA **but not with the KPO**

~~it's probably related to kubernetes_async lib~~

```json
  "K8S": {
    "conn_type": "kubernetes",
    "extra": "{\"extra__kubernetes__in_cluster\": false, \"extra__kubernetes__kube_config_path\": \"/usr/local/airflow/include/.kube/config\", \"extra__kubernetes__namespace\": \"default\", \"extra__kubernetes__cluster_context\": \"kind-kind\", \"extra__kubernetes__disable_verify_ssl\": false, \"extra__kubernetes__disable_tcp_keepalive\": false}"
  }
```

```
[2022-11-02, 16:02:40 UTC] {base.py:71} INFO - Using connection ID 'K8S' for task execution.
[2022-11-02, 16:02:40 UTC] {kubernetes_pod.py:380} INFO - Found matching pod airflow-test-pod-c740ff0eb5634a1c9bc44f4650a4128a with labels {'airflow_kpo_in_cluster': 'False', 'airflow_version': '2.4.2', 'dag_id': 'kubernetes_dag', 'kubernetes_pod_operator': 'True', 'run_id': 'scheduled__2022-11-01T0000000000-1da5bbba7', 'task_id': 'task-one', 'try_number': '4'}
[2022-11-02, 16:02:40 UTC] {kubernetes_pod.py:381} INFO - `try_number` of task_instance: 4
[2022-11-02, 16:02:40 UTC] {kubernetes_pod.py:382} INFO - `try_number` of pod: 4
[2022-11-02, 16:02:40 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 111, in trigger_reentry
    self.raise_for_trigger_status(event)
  File "/home/airflow/.local/lib/python3.10/site-packages/astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 51, in raise_for_trigger_status
    raise AirflowException(description)
airflow.exceptions.AirflowException: Trigger WaitContainerTrigger failed with exception ConfigException.
trigger exception message: Invalid kube-config file. Expected key current-context in kube-config
trigger traceback:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/astronomer/providers/cncf/kubernetes/triggers/wait_container.py", line 119, in run
    async with await hook.get_api_client_async() as api_client:
  File "/home/airflow/.local/lib/python3.10/site-packages/astronomer/providers/cncf/kubernetes/hooks/kubernetes.py", line 72, in get_api_client_async
    kube_client = await self._load_config()
  File "/home/airflow/.local/lib/python3.10/site-packages/astronomer/providers/cncf/kubernetes/hooks/kubernetes.py", line 65, in _load_config
    await config.load_kube_config(
  File "/home/airflow/.local/lib/python3.10/site-packages/kubernetes_asyncio/config/kube_config.py", line 566, in load_kube_config
    loader = _get_kube_config_loader_for_yaml_file(
  File "/home/airflow/.local/lib/python3.10/site-packages/kubernetes_asyncio/config/kube_config.py", line 530, in _get_kube_config_loader_for_yaml_file
    return KubeConfigLoader(
  File "/home/airflow/.local/lib/python3.10/site-packages/kubernetes_asyncio/config/kube_config.py", line 148, in __init__
    self.set_active_context(active_context)
  File "/home/airflow/.local/lib/python3.10/site-packages/kubernetes_asyncio/config/kube_config.py", line 159, in set_active_context
    context_name = self._config['current-context']
  File "/home/airflow/.local/lib/python3.10/site-packages/kubernetes_asyncio/config/kube_config.py", line 415, in __getitem__
    raise ConfigException(
kubernetes_asyncio.config.config_exception.ConfigException: Invalid kube-config file. Expected key current-context in kube-config

```

**To Reproduce**
```python
from airflow import DAG
# from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
from astronomer.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperatorAsync

dag = DAG(dag_id="kubernetes_dag")
with dag:
    KubernetesPodOperatorAsync(
        task_id="task-one",
        namespace="default",
        kubernetes_conn_id="K8S",
        name="airflow-test-pod",
        image="alpine:3.16.2",
        cmds=["sh", "-c", "echo hello"]
    )

```

**Expected behavior**
KPO and KPOA should work with the same kubernetes_conn

**Comment by pankajastro** [comment]
yeah, `kubernetes_conn_id` has been recently got added to Airflow. Thank you for raising this issue.

**Comment by raphaelauv** [comment]
if I set the parameter `config_file` it then work

```python
    KubernetesPodOperatorAsync(
        task_id="task-one",
        namespace="default",
        kubernetes_conn_id="kubernetes_default",
        config_file="/usr/local/airflow/include/.kube/config",
        ...
```

**Comment by bharanidharan14** [comment]
@raphaelauv Can tell us what version `apache-airflow-providers-cncf-kubernetes` you are using?

**Comment by raphaelauv** [comment]
apache-airflow-providers-cncf-kubernetes==4.4.0

**Comment by bharanidharan14** [comment]
@raphaelauv I tested with `apache-airflow-providers-cncf-kubernetes==4.4.0` same version but still, sync is also not working without the `config_file`

**Comment by raphaelauv** [comment]
my example with the KPO work with airflow 2.4.2 and apache-airflow-providers-cncf-kubernetes==4.4.0  , 

could you check again

**Comment by raphaelauv** [comment]
![Screenshot from 2022-11-16 10-47-52](https://user-images.githubusercontent.com/10202690/202147110-484cb9ce-0714-44ca-a4f8-b69528ff7720.png)
![Screenshot from 2022-11-16 10-47-44](https://user-images.githubusercontent.com/10202690/202147121-b6134f04-d781-4bc9-8163-1c7510674757.png)
![Screenshot from 2022-11-16 10-46-21](https://user-images.githubusercontent.com/10202690/202147129-4f91446a-da35-472b-bd86-a488387b16b4.png)
![Screenshot from 2022-11-16 10-46-11](https://user-images.githubusercontent.com/10202690/202147133-f3541c14-f025-4ff7-aab6-a2b2aae92255.png)
![Screenshot from 2022-11-16 10-45-58](https://user-images.githubusercontent.com/10202690/202147139-a6319e7b-6db7-4b60-9c33-bdb02ce06477.png)
