### ISSUE TITLE
GCP DataProc failing with Astronomer Runtime 7.0.0-alpha5 based on Airflow 2.5.0.dev2384+astro.1 image

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#788]
Seeing this error immediately in the UI Logs and then logs disappear:
```
[2022-11-30, 09:54:39 UTC]    INFO | Filling up the DagBag from /usr/local/airflow/dags/example_dataproc.py
[2022-11-30, 09:54:39 UTC] WARNING | Dependency <Task(DataprocCreateClusterOperatorAsync): create_cluster>, update_cluster already registered for DAG: example_gcp_dataproc
[2022-11-30, 09:54:39 UTC] WARNING | Dependency <Task(DataprocUpdateClusterOperatorAsync): update_cluster>, create_cluster already registered for DAG: example_gcp_dataproc
[2022-11-30, 09:54:39 UTC]    INFO | Running <TaskInstance: example_gcp_dataproc.create_cluster dataproc_dag_example_gcp_dataproc_2022-11-30 [queued]> on host 172.20.31.151
[2022-11-30, 09:54:39 UTC]    INFO | Dependencies all met for <TaskInstance: example_gcp_dataproc.create_cluster dataproc_dag_example_gcp_dataproc_2022-11-30 [queued]>
[2022-11-30, 09:54:39 UTC]    INFO | Dependencies all met for <TaskInstance: example_gcp_dataproc.create_cluster dataproc_dag_example_gcp_dataproc_2022-11-30 [queued]>
[2022-11-30, 09:54:39 UTC]    INFO | 
--------------------------------------------------------------------------------
[2022-11-30, 09:54:39 UTC]    INFO | Starting attempt 1 of 3
[2022-11-30, 09:54:39 UTC]    INFO | 
--------------------------------------------------------------------------------
Exception in thread Thread-244:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/listener.py", line 89, in on_running
    task_instance_copy = copy.deepcopy(task_instance)
  File "/usr/local/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1166, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/local/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/dag.py", line 2130, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1166, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/local/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.9/copy.py", line 264, in _reconstruct
    y = func(*args)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: <object object at 0x7f119d84fea0> is not a valid _MethodDefault
[2022-11-30, 09:54:39 UTC]    INFO | Executing <Task(DataprocCreateClusterOperatorAsync): create_cluster> on 2022-11-30 00:00:00+00:00
[2022-11-30, 09:54:39 UTC]    INFO | Started process 2425 to run task
[2022-11-30, 09:54:39 UTC]    INFO | Running: ['airflow', 'tasks', 'run', 'example_gcp_dataproc', 'create_cluster', 'dataproc_dag_example_gcp_dataproc_2022-11-30', '--job-id', '46724', '--raw', '--subdir', 'DAGS_FOLDER/example_dataproc.py', '--cfg-path', '/tmp/tmpjjx18jd3']
[2022-11-30, 09:54:39 UTC]    INFO | Job 46724: Subtask create_cluster
[2022-11-30, 09:54:39 UTC]    INFO | Running <TaskInstance: example_gcp_dataproc.create_cluster dataproc_dag_example_gcp_dataproc_2022-11-30 [running]> on host 172.20.31.151
[2022-11-30, 09:54:39 UTC]    INFO | Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_gcp_dataproc
AIRFLOW_CTX_TASK_ID=create_cluster
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=dataproc_dag_example_gcp_dataproc_2022-11-30
```

**Comment by rajaths010494** [comment]
https://astronomer.zendesk.com/agent/tickets/14526 i have created a zendesk ticket for the cre team to look at it. It runs fine locally with the same image quay.io/astronomer/astro-runtime-dev:7.0.0-alpha5-base
but shows the warning message in below screenshot
![image.png](https://images.zenhubusercontent.com/61cd5705d341327dd82ca4b5/ab6e97fe-5d1a-478e-8378-7104d92c0338)

**Comment by rajaths010494** [comment]
with quay.io/astronomer/astro-runtime-dev:7.0.0-alpha7-base image, all the dags ran fine in Astro cloud.

**Comment by pankajkoti** [comment]
Thanks @rajaths010494 for taking care of this!
