### ISSUE TITLE
S3KeyTrigger: yield TriggerEvent twice one success and one error

### ISSUE THREAD

**Issue by boltonidze** [astronomer/astronomer-providers#915]
**Describe the bug**

I try to create sensor with `S3KeySensorAsync`:
```python
sensor = S3KeySensorAsync(
            wildcard_match=False,
            task_id=f"evet_exist",
            bucket_key="s3://my_path/_SUCCESS",
            soft_fail=False,
            timeout=75 * 60,
            poke_interval=60,
        )
```

I guess there are two bugs in S3KeyTrigger:
1. When check_fn = None, i see in logs two TriggerEvent - one with success status and another with error status:
```
[2023-03-07 13:32:30,215] {triggerer_job.py:362} INFO - Trigger <astronomer.providers.amazon.aws.triggers.s3.S3KeyTrigger bucket_name=None, bucket_key=['s3://my_path/_SUCCESS'], wildcard_match=False, check_fn=None, aws_conn_id=aws_default, hook_params={'hook_params': {'verify': None}}, poke_interval=60> (ID 1086) fired: TriggerEvent<{'status': 'success'}>
[2023-03-07 13:32:30,222] {triggerer_job.py:362} INFO - Trigger <astronomer.providers.amazon.aws.triggers.s3.S3KeyTrigger bucket_name=None, bucket_key=['s3://my_path/_SUCCESS'], wildcard_match=False, check_fn=None, aws_conn_id=aws_default, hook_params={'hook_params': {'verify': None}}, poke_interval=60> (ID 1086) fired: TriggerEvent<{'status': 'error', 'message': 'expected string or bytes-like object'}>
```

I think it's going on because we need `else` in this part of code in S3KeyTrigger class
```python
if self.check_fn is None:
    yield TriggerEvent({"status": "success"})
# need "else" here otherwise code below runs
s3_objects = await hook.get_files(
    client, self.bucket_name, self.bucket_key, self.wildcard_match
)
yield TriggerEvent({"status": "success", "s3_objects": s3_objects})

```

2. I didn't understand what does error "expected string or bytes-like object" mean. After that i added traceback in the exception and saw the full stacktrace:
```
[2023-03-07 13:32:30,215] {triggerer_job.py:362} INFO - Trigger <astronomer.providers.amazon.aws.triggers.s3.S3KeyTrigger bucket_name=None, bucket_key=['s3://my_path/_SUCCESS'], wildcard_match=False, check_fn=None, aws_conn_id=aws_default, hook_params={'hook_params': {'verify': None}}, poke_interval=60> (ID 1086) fired: TriggerEvent<{'status': 'success'}>
[2023-03-07 13:32:30,220] {loaders.py:180} DEBUG - Loading JSON file: /home/***/.local/lib/python3.8/site-packages/botocore/data/s3/2006-03-01/paginators-1.json
[2023-03-07 13:32:30,221] {hooks.py:63} DEBUG - Event before-parameter-build.s3.ListObjectsV2: calling handler <function set_list_objects_encoding_type_url at 0x7ff37c784c10>
[2023-03-07 13:32:30,221] {hooks.py:63} DEBUG - Event before-parameter-build.s3.ListObjectsV2: calling handler <function validate_bucket_name at 0x7ff37c785940>
[2023-03-07 13:32:30,222] {s3.py:81} DEBUG - Traceback (most recent call last):
  File "/home/***/.local/lib/python3.8/site-packages/astronomer/providers/amazon/aws/triggers/s3.py", line 72, in run
    s3_objects = await hook.get_files(
  File "/home/***/.local/lib/python3.8/site-packages/astronomer/providers/amazon/aws/hooks/s3.py", line 227, in get_files
    async for page in response:
  File "/home/***/.local/lib/python3.8/site-packages/aiobotocore/paginate.py", line 30, in __anext__
    response = await self._make_request(current_kwargs)
  File "/home/***/.local/lib/python3.8/site-packages/aiobotocore/client.py", line 321, in _make_api_call
    request_dict = await self._convert_to_request_dict(
  File "/home/***/.local/lib/python3.8/site-packages/aiobotocore/client.py", line 383, in _convert_to_request_dict
    api_params = await self._emit_api_params(
  File "/home/***/.local/lib/python3.8/site-packages/aiobotocore/client.py", line 416, in _emit_api_params
    await self.meta.events.emit(
  File "/home/***/.local/lib/python3.8/site-packages/aiobotocore/hooks.py", line 66, in _emit
    response = await resolve_awaitable(handler(**kwargs))
  File "/home/***/.local/lib/python3.8/site-packages/botocore/handlers.py", line 269, in validate_bucket_name
    if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
TypeError: expected string or bytes-like object
[2023-03-07 13:32:30,222] {s3.py:82} DEBUG - <traceback object at 0x7ff35c69ff80>
[2023-03-07 13:32:30,222] {triggerer_job.py:362} INFO - Trigger <astronomer.providers.amazon.aws.triggers.s3.S3KeyTrigger bucket_name=None, bucket_key=['s3://joom my_path/_SUCCESS'], wildcard_match=False, check_fn=None, aws_conn_id=aws_default, hook_params={'hook_params': {'verify': None}}, poke_interval=60> (ID 1086) fired: TriggerEvent<{'status': 'error', 'message': 'expected string or bytes-like object'}>
```
The error occurs cause i don't pass bucket_key, but in the description in S3KeySensorAsync, I read that:
```python
:param bucket_name: Name of the S3 bucket. Only needed when ``bucket_key``
    is not provided as a full s3:// url. When specified, all the keys passed to ``bucket_key``
    refers to this bucket
```

if i pass the bucket_key parameter explicitly into my sensor then the error disappears.

**To Reproduce**
1. Create task with `S3KeySensorAsync ` as in description bug section
2. Run this trigger and check the triggerer debug logs.

Python packages:
```
apache-airflow==2.4.3
astronomer-providers==1.15.0
aiobotocore==2.4.2
boto3==1.24.59
botocore==1.27.59
```

**Expected behavior**
It seems that when check_fn is None S3KeyTrigger should return only one TriggerEvent.
And i don't about second error - because i was confused when read the description of bucket_name parameter. Maybe it's not a bug and i should pass the bucket_key parameter explicitly.

**Comment by phanikumv** [comment]
Thank you @boltonidze for opening the issue !

**Comment by rajaths010494** [comment]
Yes, the bucket key needs to be passed for the second error.
first error i have created the PR https://github.com/astronomer/astronomer-providers/pull/925
